def qustions():
    c=0
    import time
    print("WELCOME TO THE QUIZ ROUND!!!");
    cc=input("ENTER YOUR CC CODE: ");
    print("RULES:")
    print("1) No peeping allowed.")
    print("2) Use of the internet is strictly prohibited.")
    print("3) No abusive language.")
    print("4) No electronic devices are permitted during the course of the quiz. ")
    print("\n")
    print("LET GAMES BEGIN!!!!")
    print("\n")
    """print("1) What is the largest joint in the human body ?")
    print("\n")
    time1=time.time()
    print("a)Knee         b)Elbow ")
    print("c)Knuckles     d)Pelvic girdle")
    ans1=input(" ")
    time2=time.time()
    time3=time2-time1
    ans1=ans1.lower()
    if((time2-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        exit()
    print("__________________________________________")
    print("2) What does ""SIM"" stand for?")
    print("\n")
    time4=time.time()
    print("a)Subscriber internet module    b)Social interconnect module")
    print("c)subscriber identity module    d)Special identity module")
    ans2=input(" ")
    time5=time.time()
    time6=time5-time4
    ans2=ans2.lower()
    if((time5-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        exit()
    print("__________________________________________")
    print("3) The smallest bone in the human body is the?")
    print("\n")
    time7=time.time()
    print("a)Radius    b)Ulna")
    print("c)Stapes    d)Skull")
    ans3=input(" ")
    time8=time.time()
    time9=time8-time7
    ans3=ans3.lower()
    if((time8-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer1(ans3,time9)
        exit()
    print("__________________________________________")
    print("4) Which manufacturing company produced the first camera phone, called the J-phone,that could send photos over cellular network?")
    print("\n")
    time10=time.time()
    print("a)Motorola   b)Reliance")
    print("c)Nokia      d)Sharp")
    ans4=input(" ")
    time11=time.time()
    time12=time11-time10
    ans4=ans4.lower()
    if((time11-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        exit()
    print("__________________________________________")
    print("5) What was NEW YORK called before it was new york?")
    print("\n")
    time13=time.time()
    print("a)Aleppo   b)New Amsterdam")
    print("c)Bybls    d)Faiyum")
    ans5=input(" ")
    time14=time.time()
    time15=time14-time13
    ans5=ans5.lower()
    if((time14-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        exit()
    print("__________________________________________")
    print("6) Earlier, photographers use to make their images on which of the following material?")
    print("\n")
    time16=time.time()
    print("a)Wall    b)Paper")
    print("c)Wood    d)Glass")
    ans6=input(" ")
    time17=time.time()
    time18=time17-time16
    ans6=ans6.lower()
    if((time17-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        exit()
    print("__________________________________________")
    print("7) A network designed to allow communication within an organization is called  as : ")
    print("\n")
    time19=time.time()
    print("a)internet   b)inter connection")
    print("c)intranet    d)inter connected networks")
    ans7=input(" ")
    time20=time.time()
    time21=time20-time19
    ans7=ans7.lower()
    if((time20-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        exit()
    print("__________________________________________")
    print("8) Which was the first search engine on internet ?")
    print("\n")
    time22=time.time()
    print("a)Archie   b)Google")
    print("c)Yahoo    d)Bing")
    ans8=input(" ")
    time23=time.time()
    time24=time23-time22
    ans8=ans8.lower()
    if((time23-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        exit()
    print("__________________________________________")
    print("9) Which is the first web browser invented in 1990 ? ")
    print("\n")
    time25=time.time()
    print("a)Nexux   b)Opera")
    print("c)Lynx    d)Konoqueror")
    ans9=input(" ")
    time26=time.time()
    time27=time26-time25
    ans9=ans9.lower()
    if((time26-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        exit()
    print("__________________________________________")
    print("10) Which day is celebrated as world computer literacy day ? ")
    print("\n")
    time28=time.time()
    print("a)December 1   b)December 2")
    print("c)January 9    d)June 10")
    ans10=input(" ")
    time29=time.time()
    time30=time29-time28
    ans10=ans10.lower()
    if((time29-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        exit()
    print("__________________________________________")
    print("11) Do no evil; is tag line of ........? ")
    print("\n")
    time31=time.time()  
    print("a)Safari    b)Yahoo")
    print("c)Google    d)Opera")
    ans11=input(" ")
    time32=time.time()
    time33=time32-time31
    ans11=ans11.lower()
    if((time32-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        exit()
    print("__________________________________________")
    print("12) What is the extension of the pdf ? ")
    print("\n")
    time34=time.time()
    print("a)Portable dictionary format   b)Portable document format")
    print("c)Portable directory format   d)Portable document file")
    ans12=input(" ")
    time35=time.time()
    time36=time35-time34
    ans12=ans12.lower()
    if((time35-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        exit()
    print("__________________________________________")
    print("13) When was the first smart phone launched ?")
    print("\n")
    time37=time.time()
    print("a)1990   b)1980")
    print("c)1992   d)1982")
    ans13=input(" ")
    time38=time.time()
    time39=time38-time37
    ans13=ans13.lower()
    if((time38-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        exit()
    print("__________________________________________")
    print("14) Word length of the microcomputers ? ")
    print("\n")
    time40=time.time()
    print("a)8-16 bit   b)16-16 bit")
    print("c)8-32 bit   d)16-32 bit")
    ans14=input(" ")
    time41=time.time()
    time42=time41-time40
    ans14=ans14.lower()
    if((time41-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        answer14(ans14,time42)
        exit()
    print("__________________________________________")
    print("15) The technology related to light for data storage is ? ")
    print("\n")
    time43=time.time()
    print("a)Analog data storage   b)Fiber optics")
    print("c)Light storage         d)Optical data storage")
    ans15=input(" ")
    time44=time.time()
    time45=time44-time43
    ans15=ans15.lower()
    if((time44-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        answer14(ans14,time42)
        answer15(ans15,time45)
        exit()
    print("__________________________________________")
    print("16) What is the next term in the following sequence: 1,1,28,2,8,6,992,1,3,2,16256,2,16,16,5232,64 ? ")
    print("\n")
    time46=time.time()
    print("a)985627   b)36")
    print("c)19542    d)24")
    ans16=input(" ")
    time47=time.time()
    time48=time47-time46
    ans16=ans16.lower()
    if((time47-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        answer14(ans14,time42)
        answer15(ans15,time45)
        answer16(ans16,time48)
        exit()
    print("__________________________________________")
    print("17) Some months have 31 days; how many have 28 ? ")
    print("\n")
    time49=time.time()
    print("a)1   b)12")
    print("c)3   d)9")
    ans17=input(" ")
    time50=time.time()
    time51=time50-time49
    ans17=ans17.lower()
    if((time50-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        answer14(ans14,time42)
        answer15(ans15,time45)
        answer16(ans16,time48)
        answer17(ans17,time51)
        exit()
    print("__________________________________________")
    print("18) A doctor gives you 3 pills telling you to take one every half an hour. How many minutes will the pills last ? ")
    print("\n")
    time52=time.time()
    print("a)20   b)30")
    print("c)80   d)60")
    ans18=input(" ")
    time53=time.time()
    time54=time53-time52
    ans18=ans18.lower()
    if((time53-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        answer14(ans14,time42)
        answer15(ans15,time45)
        answer16(ans16,time48)
        answer17(ans17,time51)
        answer18(ans18,time54)
        exit()
    print("__________________________________________")
    print("19) If there are 3 apples and you take 2 away, how many do you have ? ")
    print("\n")
    time55=time.time()
    print("a)1   b)2")
    print("c)3   d)5")
    ans19=input(" ")
    time56=time.time()
    time57=time56-time55
    ans19=ans19.lower()
    if((time56-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        answer14(ans14,time42)
        answer15(ans15,time45)
        answer16(ans16,time48)
        answer17(ans17,time51)
        answer18(ans18,time54)
        answer19(ans19,time57)
        exit()
    print("__________________________________________")
    print("20) Divide 30 by 1/2 and add 10. What is the answer ? ")
    print("\n")
    time58=time.time()
    print("a)10   b)70")
    print("c)25   d)50")
    ans20=input(" ")
    time59=time.time()
    time60=time59-time58
    ans20=ans20.lower()
    print("time exceed !! you are not allow to answer:")
    print("team: ",cc)
    answer1(ans1,time3)
    answer2(ans2,time6)
    answer3(ans3,time9)
    answer4(ans4,time12)
    answer5(ans5,time15)
    answer6(ans6,time18)
    answer7(ans7,time21)
    answer8(ans8,time24)
    answer9(ans9,time27)
    answer10(ans10,time30)
    answer11(ans11,time33)
    answer12(ans12,time36)
    answer13(ans13,time39)
    answer14(ans14,time42)
    answer15(ans15,time45)
    answer16(ans16,time48)
    answer17(ans17,time51)
    answer18(ans18,time54)
    answer19(ans19,time57)
    answer20(ans20,time60)
    sum=(time3+time6+time9+time12+time15+time18+time21+time24+time27+time30+time33+time36+time39+time42+time45+time48+time51+time54+time57+time60)
    print("total time taken is: ",sum)
    time.sleep(5)
    print("__________________________________________")"""
    print("21) A farmer has 17 sheeps, and all but 9 die. How many are left ? ")
    print("\n")
    time61=time.time()
    print("a)9   b)1")
    print("c)8   d)5")
    ans21=input(" ")
    time62=time.time()
    time63=time62-time61
    ans21=ans21.lower()
    if((time62-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        answer14(ans14,time42)
        answer15(ans15,time45)
        answer16(ans16,time48)
        answer17(ans17,time51)
        answer18(ans18,time54)
        answer19(ans19,time57)
        answer20(ans20,time60)
        answer21(ans21,time63)
        exit()
    print("__________________________________________")
    print("22) Take 1000 and add 40 to it, now add another 1000, now add 30, add another 1000, now add 20, now add anoher 1000, now add 10. What is the total ? ")
    print("\n")
    time64=time.time()
    print("a)5000   b)5100")
    print("c)4100   d)4000")
    ans22=input(" ")
    time65=time.time()
    time66=time65-time64
    ans22=ans22.lower()
    if((time65-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        answer14(ans14,time42)
        answer15(ans15,time45)
        answer16(ans16,time48)
        answer17(ans17,time51)
        answer18(ans18,time54)
        answer19(ans19,time57)
        answer20(ans20,time60)
        answer21(ans21,time63)
        answer22(ans22,time66)
        exit()
    print("__________________________________________")
    print("23) Mary's father has 5 daughters and 3 sons total 8 children 1) nene 2)nono 3)nino 4)hero 5)amir 6)sailesh 7)nobi what is the name of 8) ? ")
    print("\n")
    time67=time.time()
    print("a)Neno   b)Mary")
    print("c)Nini   d)Hero")
    ans23=input(" ")
    time68=time.time()
    time69=time68-time67
    ans23=ans23.lower()
    if((time68-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        answer14(ans14,time42)
        answer15(ans15,time45)
        answer16(ans16,time48)
        answer17(ans17,time51)
        answer18(ans18,time54)
        answer19(ans19,time57)
        answer20(ans20,time60)
        answer21(ans21,time63)
        answer22(ans22,time66)
        answer23(ans23,time69)
        exit()
    print("__________________________________________")
    print("24) How many days are there in x weeks and x days ? (in terms of x) ")
    print("\n")
    time70=time.time()
    print("a)7x^2   b)8x")
    print("c)7   d)14x")
    ans24=input(" ")
    time71=time.time()
    time72=time71-time70
    ans24=ans24.lower()
    if((time71-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        answer14(ans14,time42)
        answer15(ans15,time45)
        answer16(ans16,time48)
        answer17(ans17,time51)
        answer18(ans18,time54)
        answer19(ans19,time57)
        answer20(ans20,time60)
        answer21(ans21,time63)
        answer22(ans22,time66)
        answer23(ans23,time69)
        answer24(ans24,time72)
        exit()
    print("__________________________________________")
    print("25) The last day of the century cannot be ? ")
    print("\n")
    time73=time.time()
    print("a)Monday   b)Wednesday")
    print("c)Friday   d)Tuesday")
    ans25=input(" ")
    time74=time.time()
    time75=time74-time73
    ans25=ans25.lower()
    if((time74-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        answer14(ans14,time42)
        answer15(ans15,time45)
        answer16(ans16,time48)
        answer17(ans17,time51)
        answer18(ans18,time54)
        answer19(ans19,time57)
        answer20(ans20,time60)
        answer21(ans21,time63)
        answer22(ans22,time66)
        answer23(ans23,time69)
        answer24(ans24,time72)
        answer25(ans25,time75)
        exit()
    print("__________________________________________")
    print("26) who wrote Devdas ? ")
    print("\n")
    time76=time.time()
    print("a)kalidas                       b)surdas")
    print("c)Saratchandra chattopadhyay    d)Binhutibhushan Bandopadhyay")
    ans26=input(" ")
    time77=time.time()
    time78=time74-time73
    ans26=ans26.lower()
    if((time77-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        answer14(ans14,time42)
        answer15(ans15,time45)
        answer16(ans16,time48)
        answer17(ans17,time51)
        answer18(ans18,time54)
        answer19(ans19,time57)
        answer20(ans20,time60)
        answer21(ans21,time63)
        answer22(ans22,time66)
        answer23(ans23,time69)
        answer24(ans24,time72)
        answer25(ans25,time75)
        answer26(ans26,time78)
        exit()
    print("__________________________________________")
    print("27) Epsom(England) is a place associated with :  ")
    print("\n")
    time79=time.time()
    print("a)Snooker   b)Shooting")
    print("c)pPolo      d)Horse racing")
    ans27=input(" ")
    time80=time.time()
    time81=time80-time79
    ans27=ans27.lower()
    if((time80-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        answer14(ans14,time42)
        answer15(ans15,time45)
        answer16(ans16,time48)
        answer17(ans17,time51)
        answer18(ans18,time54)
        answer19(ans19,time57)
        answer20(ans20,time60)
        answer21(ans21,time63)
        answer22(ans22,time66)
        answer23(ans23,time69)
        answer24(ans24,time72)
        answer25(ans25,time75)
        answer26(ans26,time78)
        answer27(ans27,time81)
        exit()
    print("__________________________________________")
    print("28) A is two years older than B who is twice as old as C. If the total of the ages of A,B and C be 27, then how old is B ? ")
    print("\n")
    time82=time.time()
    print("a)7     b)10")
    print("c)9     d)11")
    ans28=input(" ")
    time83=time.time()
    time84=time83-time82
    ans28=ans28.lower()
    if((time83-time1)>1800):
        print("time exceed !! you are not allow to answer: ")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        answer14(ans14,time42)
        answer15(ans15,time45)
        answer16(ans16,time48)
        answer17(ans17,time51)
        answer18(ans18,time54)
        answer19(ans19,time57)
        answer20(ans20,time60)
        answer21(ans21,time63)
        answer22(ans22,time66)
        answer23(ans23,time69)
        answer24(ans24,time72)
        answer25(ans25,time75)
        answer26(ans26,time78)
        answer27(ans27,time81)
        answer28(ans28,time84)
        exit()
    print("__________________________________________")
    print("29) Who among the following indians was conferred the prestigious,""National medal of arts and humanities,awarded by US president in february 2012")
    print("\n")
    time85=time.time()
    print("a)Dr.Montek Singh Ahluwalia    b)Dr.Amartya Sen")
    print("c)D.D Subbaraor                d)Shri Nr Narayan Murthy")
    ans29=input(" ")
    time86=time.time()
    time87=time86-time85
    ans29=ans29.lower()
    if((time86-time1)>1800):
        print("team: ",cc)
        print("time exceed !! you are not allow to answer:")
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33) 
        answer12(ans12,time36)
        answer13(ans13,time39)
        answer14(ans14,time42)
        answer15(ans15,time45)
        answer16(ans16,time48)
        answer17(ans17,time51)
        answer18(ans18,time54)
        answer19(ans19,time57)
        answer20(ans20,time60)
        answer21(ans21,time63)
        answer22(ans22,time66)
        answer23(ans23,time69)
        answer24(ans24,time72)
        answer25(ans25,time75)
        answer26(ans26,time78)
        answer27(ans27,time81)
        answer28(ans28,time84)
        answer29(ans29,time87)
        exit()
    print("__________________________________________")
    print("30) Gundecha brothers are well known exponents of which among the following styles of hindustani classical music ?")
    print("\n")
    time88=time.time()
    print("a)Khayal    b)Dhrupad")
    print("c)Tharana   d)Thumri")
    ans30=input(" ")
    time89=time.time()
    time90=time89-time88
    print("team: ",cc)
    ans30=ans30.lower()
    answer1(ans1,time3)
    answer2(ans2,time6)
    answer3(ans3,time9)
    answer4(ans4,time12)
    answer5(ans5,time15)
    answer6(ans6,time18)
    answer7(ans7,time21)
    answer8(ans8,time24)
    answer9(ans9,time27)
    answer10(ans10,time30)
    answer11(ans11,time33) 
    answer12(ans12,time36)
    answer13(ans13,time39)
    answer14(ans14,time42)
    answer15(ans15,time45)
    answer16(ans16,time48)
    answer17(ans17,time51)
    answer18(ans18,time54)
    answer19(ans19,time57)
    answer20(ans20,time60)
    answer21(ans21,time63)
    answer22(ans22,time66)
    answer23(ans23,time69)
    answer24(ans24,time72)
    answer25(ans25,time75)
    answer26(ans26,time78)
    answer27(ans27,time81)
    answer28(ans28,time84)
    answer29(ans29,time87)
    answer30(ans30,time90)
    print("11) DEH,GDJ,(?),EJO,GLQ,INS?")
    print("\n")
    time1=time.time()
    print("a)FLR         b)FIS")
    print("c)FKO         d)FIL")
    ans1=input(" ")
    time2=time.time()
    time3=time2-time1
    ans1=ans1.lower()
    if((time2-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        exit()
    print("__________________________________________")
    print("12)RAP,MAP,HOT FUN,(?)")
    print("\n")
    time4=time.time()
    print("a)HNE    b)PGI")
    print("c)STN    d)CAT")
    ans2=input(" ")
    time5=time.time()
    time6=time5-time4
    ans2=ans2.lower()
    if((time5-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        exit()
    print("__________________________________________")
    print("13) A,B and C are intelligent,A,D and E are laborious and D,C and E are honest and A,B,and E are ambitious. which of the following are not honest?")
    print("\n")
    time7=time.time()
    print("a)A and B    b)C and A")
    print("c)A and D    d)C,A and B")
    ans3=input(" ")
    time8=time.time()
    time9=time8-time7
    ans3=ans3.lower()
    if((time8-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer1(ans3,time9)
        exit()
    print("__________________________________________")
    print("14)A,B,C,D,E and F were playing cards,A's father,mother and uncle were in the group. There were two females also: B was the mother of A who scored higher than her husband.D scored higher than E but less than F.E's nephew scored minimum.A's father scored more than F but even then he could not win. who win the game?")
    print("\n")
    time10=time.time()
    print("a)E   b)B")
    print("c)C   d)F")
    ans4=input(" ")
    time11=time.time()
    time12=time11-time10
    ans4=ans4.lower()
    if((time11-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        exit()
    print("__________________________________________")
    print("15)78,65,75,62,72...?")
    print("\n")
    time13=time.time()
    print("a)61   b)65")
    print("c)64    d)59")
    ans5=input(" ")
    time14=time.time()
    time15=time14-time13
    ans5=ans5.lower()
    if((time14-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        exit()
    print("__________________________________________")
    print("16) ?")
    print("\n")
    time16=time.time()
    print("a)Wall    b)Paper")
    print("c)Wood    d)Glass")
    ans6=input(" ")
    time17=time.time()
    time18=time17-time16
    ans6=ans6.lower()
    if((time17-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        exit()
    print("__________________________________________")
    print("7) A network designed to allow communication within an organization is called  as : ")
    print("\n")
    time19=time.time()
    print("a)internet   b)inter connection")
    print("c)intranet    d)inter connected networks")
    ans7=input(" ")
    time20=time.time()
    time21=time20-time19
    ans7=ans7.lower()
    if((time20-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        exit()
    print("__________________________________________")
    print("8) Which was the first search engine on internet ?")
    print("\n")
    time22=time.time()
    print("a)Archie   b)Google")
    print("c)Yahoo    d)Bing")
    ans8=input(" ")
    time23=time.time()
    time24=time23-time22
    ans8=ans8.lower()
    if((time23-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        exit()
    print("__________________________________________")
    print("9) Which is the first web browser invented in 1990 ? ")
    print("\n")
    time25=time.time()
    print("a)Nexux   b)Opera")
    print("c)Lynx    d)Konoqueror")
    ans9=input(" ")
    time26=time.time()
    time27=time26-time25
    ans9=ans9.lower()
    if((time26-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)"""
    print("11) BEH,DGJ,(?),EJO,GLQ,INS? ")
    print("\n")
    time28=time.time()
    print("a)FLR   b)FIS")
    print("c)FKO    d)FIL")
    ans10=input(" ")
    time29=time.time()
    time30=time29-time28
    ans10=ans10.lower()
    if((time29-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        exit()
    print("__________________________________________")
    print("11) Do no evil; is tag line of ........? ")
    print("\n")
    time31=time.time()  
    print("a)Safari    b)Yahoo")
    print("c)Google    d)Opera")
    ans11=input(" ")
    time32=time.time()
    time33=time32-time31
    ans11=ans11.lower()
    if((time32-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        exit()
    print("__________________________________________")
    print("12) What is the extension of the pdf ? ")
    print("\n")
    time34=time.time()
    print("a)Portable dictionary format   b)Portable document format")
    print("c)Portable directory format   d)Portable document file")
    ans12=input(" ")
    time35=time.time()
    time36=time35-time34
    ans12=ans12.lower()
    if((time35-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        exit()
    print("__________________________________________")
    print("13) When was the first smart phone launched ?")
    print("\n")
    time37=time.time()
    print("a)1990   b)1980")
    print("c)1992   d)1982")
    ans13=input(" ")
    time38=time.time()
    time39=time38-time37
    ans13=ans13.lower()
    if((time38-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        exit()
    print("__________________________________________")
    print("14) Word length of the microcomputers ? ")
    print("\n")
    time40=time.time()
    print("a)8-16 bit   b)16-16 bit")
    print("c)8-32 bit   d)16-32 bit")
    ans14=input(" ")
    time41=time.time()
    time42=time41-time40
    ans14=ans14.lower()
    if((time41-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        answer14(ans14,time42)
        exit()
    print("__________________________________________")
    print("15) The technology related to light for data storage is ? ")
    print("\n")
    time43=time.time()
    print("a)Analog data storage   b)Fiber optics")
    print("c)Light storage         d)Optical data storage")
    ans15=input(" ")
    time44=time.time()
    time45=time44-time43
    ans15=ans15.lower()
    if((time44-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        answer14(ans14,time42)
        answer15(ans15,time45)
        exit()
    print("__________________________________________")
    print("16) What is the next term in the following sequence: 1,1,28,2,8,6,992,1,3,2,16256,2,16,16,5232,64 ? ")
    print("\n")
    time46=time.time()
    print("a)985627   b)36")
    print("c)19542    d)24")
    ans16=input(" ")
    time47=time.time()
    time48=time47-time46
    ans16=ans16.lower()
    if((time47-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        answer14(ans14,time42)
        answer15(ans15,time45)
        answer16(ans16,time48)
        exit()
    print("__________________________________________")
    print("17) Some months have 31 days; how many have 28 ? ")
    print("\n")
    time49=time.time()
    print("a)1   b)12")
    print("c)3   d)9")
    ans17=input(" ")
    time50=time.time()
    time51=time50-time49
    ans17=ans17.lower()
    if((time50-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        answer14(ans14,time42)
        answer15(ans15,time45)
        answer16(ans16,time48)
        answer17(ans17,time51)
        exit()
    print("__________________________________________")
    print("18) A doctor gives you 3 pills telling you to take one every half an hour. How many minutes will the pills last ? ")
    print("\n")
    time52=time.time()
    print("a)20   b)30")
    print("c)80   d)60")
    ans18=input(" ")
    time53=time.time()
    time54=time53-time52
    ans18=ans18.lower()
    if((time53-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        answer14(ans14,time42)
        answer15(ans15,time45)
        answer16(ans16,time48)
        answer17(ans17,time51)
        answer18(ans18,time54)
        exit()
    print("__________________________________________")
    print("19) If there are 3 apples and you take 2 away, how many do you have ? ")
    print("\n")
    time55=time.time()
    print("a)1   b)2")
    print("c)3   d)5")
    ans19=input(" ")
    time56=time.time()
    time57=time56-time55
    ans19=ans19.lower()
    if((time56-time1)>1800):
        print("time exceed !! you are not allow to answer:")
        print("team: ",cc)
        answer1(ans1,time3)
        answer2(ans2,time6)
        answer3(ans3,time9)
        answer4(ans4,time12)
        answer5(ans5,time15)
        answer6(ans6,time18)
        answer7(ans7,time21)
        answer8(ans8,time24)
        answer9(ans9,time27)
        answer10(ans10,time30)
        answer11(ans11,time33)
        answer12(ans12,time36)
        answer13(ans13,time39)
        answer14(ans14,time42)
        answer15(ans15,time45)
        answer16(ans16,time48)
        answer17(ans17,time51)
        answer18(ans18,time54)
        answer19(ans19,time57)
        exit()
    print("__________________________________________")
    print("20) Divide 30 by 1/2 and add 10. What is the answer ? ")
    print("\n")
    time58=time.time()
    print("a)10   b)70")
    print("c)25   d)50")
    ans20=input(" ")
    time59=time.time()
    time60=time59-time58
    ans20=ans20.lower()
    print("time exceed !! you are not allow to answer:")
    print("team: ",cc)
    answer1(ans1,time3)
    answer2(ans2,time6)
    answer3(ans3,time9)
    answer4(ans4,time12)
    answer5(ans5,time15)
    answer6(ans6,time18)
    answer7(ans7,time21)
    answer8(ans8,time24)
    answer9(ans9,time27)
    answer10(ans10,time30)
    answer11(ans11,time33)
    answer12(ans12,time36)
    answer13(ans13,time39)
    answer14(ans14,time42)
    answer15(ans15,time45)
    answer16(ans16,time48)
    answer17(ans17,time51)
    answer18(ans18,time54)
    answer19(ans19,time57)
    answer20(ans20,time60)
    print("__________________________________________")
    sum=(time63+time66+time69+time72+time75+time78+time81+time84+time87+time90)
    print("total time taken is: ",sum)
    time.sleep(1)
    



    
"""def answer1(ans1,time3):
    if(ans1=="a"):
        print("1) correct taken time: ",time3," seconds !!")
    else:
        print("1) wrong answer taken time: ",time3)
def answer2(ans2,time6):
    if(ans2=="c"):
        print("2) correct taken time:  ",time6," seconds !!")
    else:
        print(" 2) wrong answer taken time: ",time6)
def answer3(ans3,time9):
    if(ans3=="c"):
        print(" 3) correct taken time: ",time9," seconds !!")
    else:
        print("3) wrong answer! taken time: ",time9)
def answer4(ans4,time12):
    if(ans4=="d"):
        print("4) correct  taken time: ",time12," seconds !!")
    else:
        print("4) wrong answer taken time: ",time12)
def answer5(ans5,time15):
    if(ans5=="b"):
        print("5) correct  taken time: ",time15," seconds !!")
    else:
        print("5) wrong answer taken time: ",time15)
def answer6(ans6,time18):
    if(ans6=="d"):
        print("6) correct taken time: ",time18," seconds !!")
    else:
        print("6) wrong answer time taken: ",time18)
def answer7(ans7,time21):
    if(ans7=="c"):
        print("7) correct taken time: ",time21," seconds !!")
    else:
        print("7) wrong answer taken time: ",time21)
def answer8(ans8,time24):
    if(ans8=="a"):
        print("8) correct taken time: ",time24," seconds !!")
    else:
        print("8) wrong answer! taken time ",time24)
def answer9(ans9,time27):        
    if(ans9=="a"):
        print("9) correct taken time: ",time27," seconds !!")
    else:
        print("9) wrong answer taken time: ",time27)
def answer10(ans10,time30):
    if(ans10=="b"):
        print("10) correct answer taken time: ",time30," seconds !!")
    else:
        print("10) wrong answer taken time: ",time30)
def answer11(ans11,time33):
    if(ans11=="c"):
        print("11) correct taken time:",time33," seconds !!")
    else:
        print("11) wrong answer taken time: ",time33)
def answer12(ans12,time36):
    if(ans12=="b"):
        print("12) correct taken time: ",time36," seconds !!")
    else:
        print("12) wrong answer taken time: ",time36)
def answer13(ans13,time39):
    if(ans13=="c"):
        print("13) correct taken time: ",time39," seconds !!")
    else:
        print("13) wrong answer taken time: ",time39)
def answer14(ans14,time42):
    if(ans14=="c"):
        print("14) correct taken time: ",time42," seconds !!")
    else:
        print("14) wrong answer taken time: ",time42)
def answer15(ans15,time45):
    if(ans15=="d"):
        print("15) correct answer taken time: ",time45," seconds !!")
    else:
        print("15) wrong answer taken time: ",time45)
def answer16(ans16,time48):
    if(ans16=="d"):
        print("16) correct answer taken time: ",time48," second !!")
    else:
        print("16) wrong answer taken time: ",time48)
def answer17(ans17,time51):
    if(ans17=="b"):
        print("17) correct answer taken time: ",time51," second !!")
    else:
        print("17) wrong answer taken time: ",time51)
def answer18(ans18,time54):
    if(ans18=="d"):
        print("18) correct answer taken time: ",time54," second !!")
    else:
        print("18) wrong answer taken time: ",time54)
def answer19(ans19,time57):
    if(ans19=="b"):
        print("19) correct answer taken time: ",time57," second !!")
    else:
        print("19) wrong answer taken time: ",time57)
def answer20(ans20,time60):
    if(ans20=="b"):
        print("20) correct answer taken time: ",time60," second !!")
    else:
        print("20) wrong answer taken time: ",time60)"""
def answer21(ans21,time63):
    if(ans21=="a"):
        print("1) correct answer taken time: ",time63," second !!")
    else:
        print("1) wrong answer taken time: ",time63)
def answer22(ans22,time66):
    if(ans22=="c"):
        print("2) correct answer taken time: ",time66," second !!")
    else:
        print("2) wrong answer taken time: ",time66)
def answer23(ans23,time69):
    if(ans23=="b"):
        print("3) correct answer taken time: ",time69," second !!")
    else:
        print("3) wrong answer taken time: ",time69)
def answer24(ans24,time72):
    if(ans24=="b"):
        print("4) correct answer taken time: ",time72," second !!")
    else:
        print("4) wrong answer taken time: ",time72)
def answer25(ans25,time75):
    if(ans25=="d"):
        print("5) correct answer taken time: ",time75," second !!")
    else:
        print("5) wrong answer taken time: ",time75)
def answer26(ans26,time78):
    if(ans26=="c"):
        print("6) correct answer taken time: ",time78," second !!")
    else:
        print("6) wrong answer taken time: ",time78)
def answer27(ans27,time81):
    if(ans27=="d"):
        print("7) correct answer taken time: ",time81," second !!")
    else:
        print("7) wrong answer taken time: ",time81)
def answer28(ans28,time84):
    if(ans28=="b"):
        print("8) correct answer taken time: ",time84," second !!")
    else:
        print("8) wrong answer taken time: ",time84)
def answer29(ans29,time87):
    if(ans29=="b"):
        print("9) correct answer taken time: ",time87," second !!")
    else:
        print("9) wrong answer taken time: ",time87)
def answer30(ans30,time90):
    if(ans30=="b"):
        print("10) correct answer taken time: ",time90," second !!")
    else:
        print("10) wrong answer taken time: ",time90)
#main
qustions()










